name       : pip
version    : 9.0.1
release    : 10
source     :
    - https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz : 09f243e1a7b461f654c26a725fa373211bb7ff17a9300058b205c61658ca940d
license    : MIT
component  : programming.tools
summary    : The PyPA recommended tool for installing Python packages.
description: |
    The PyPA recommended tool for installing Python packages.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
