name       : pip
version    : '18.1'
release    : 11
source     :
    - https://github.com/pypa/pip/archive/18.1.tar.gz : 3ff036bbbce30f27b0ba440134defa66a135740c9e3401bd466e7f0d8153147c
license    : MIT
component  : programming.tools
summary    : The PyPA recommended tool for installing Python packages.
description: |
    The PyPA recommended tool for installing Python packages.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
