name       : pip
version    : 20.3.4
release    : 15
source     :
    - https://github.com/pypa/pip/archive/20.3.4.tar.gz : cc21e03832d7ce96a0cf77ec1669661de35abb4366a9059fa54f1647e514ce3f
homepage   : https://pip.pypa.io/en/stable/
license    : MIT
component  : programming.tools
summary    : The PyPA recommended tool for installing Python packages
description: |
    The PyPA recommended tool for installing Python packages.
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
#check      : |
#    # requires python2 modules for scripttest csv23 and werkzeug
#    %python_test
