name       : pip
version    : 20.1.1
release    : 14
source     :
    - https://github.com/pypa/pip/archive/20.1.1.tar.gz : fa20f7632bab63162d281e555e1d40dced21f22b2578709454f9015f279a0144
license    : MIT
component  : programming.tools
summary    : The PyPA recommended tool for installing Python packages.
description: |
    The PyPA recommended tool for installing Python packages.
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
#check      : |
#    # requires scripttest to be packaged
#    %python_test
