name        : pip
version     : 7.1.2
release     : 7
source     :
    - https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz : ca047986f0528cfa975a14fb9f7f106271d4e0c3fe1ddced6c1db2e7ae57a477
license     : MIT
summary     : The PyPA recommended tool for installing Python packages.
description : |
    The PyPA recommended tool for installing Python packages.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
    - python3-setuptools
rundeps    :
    - python-setuptools
    - python3-setuptools
build      : |
    for py in "python3" "python" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python3" "python" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
