name       : pip
version    : 19.3.1
release    : 12
source     :
    - https://github.com/pypa/pip/archive/19.3.1.tar.gz : f12b7a6be2dbbfeefae5f14992c89175ef72ce0fe96452b4f66be855a12841ff
license    : MIT
component  : programming.tools
summary    : The PyPA recommended tool for installing Python packages.
description: |
    The PyPA recommended tool for installing Python packages.
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
#check      : |
#    # requires scripttest to be packaged
#    %python_test
