name       : pip
version    : 20.0.2
release    : 13
source     :
    - https://github.com/pypa/pip/archive/20.0.2.tar.gz : 00bdc118df4552f654a5ccf0bd3ff1a7d101ee7d7ac899fe9a752363b3f2f070
license    : MIT
component  : programming.tools
summary    : The PyPA recommended tool for installing Python packages.
description: |
    The PyPA recommended tool for installing Python packages.
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
#check      : |
#    # requires scripttest to be packaged
#    %python_test
